/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jquiz.panels;

import jquiz.Const;
import jquiz.MainFrame;
import jquiz.Util;

/**
 *
 * @author ratul
 */
public class CreateQuizPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form CreateQuizPanel
     */
    public CreateQuizPanel() {
        initComponents();
    }

    public CreateQuizPanel(MainFrame mainFrame) {
        this();
        setVisible(false);
        this.mainFrame = mainFrame;

        com.github.lgooddatepicker.components.TimePickerSettings durationTimePickerSettings = durationTimePicker.getSettings();
        durationTimePickerSettings.setAllowKeyboardEditing(false);
        durationTimePickerSettings.setFormatForDisplayTime(Const.DURATION_PATTERN);
        durationTimePickerSettings.setFormatForMenuTimes(Const.DURATION_PATTERN);
        durationTimePickerSettings.generatePotentialMenuTimes(
                Util.getLocalTimes(Const.MIN_DURATION, Const.MAX_DURATION, Const.STEP_DURATION));

        com.github.lgooddatepicker.components.TimePickerSettings pauseDurationTimePickerSettings = pauseDurationTimePicker.getSettings();
        pauseDurationTimePickerSettings.setAllowKeyboardEditing(false);
        pauseDurationTimePickerSettings.setFormatForDisplayTime(Const.PAUSE_DURATION_PATTERN);
        pauseDurationTimePickerSettings.setFormatForMenuTimes(Const.PAUSE_DURATION_PATTERN);
        pauseDurationTimePickerSettings.generatePotentialMenuTimes(
                Util.getLocalTimes(Const.MIN_PAUSE_DURATION, Const.MAX_PAUSE_DURATION, Const.STEP_PAUSE_DURATION));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        titleTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        durationLabel = new javax.swing.JLabel();
        durationTimePicker = new com.github.lgooddatepicker.components.TimePicker();
        pauseDurationLabel = new javax.swing.JLabel();
        pauseDurationTimePicker = new com.github.lgooddatepicker.components.TimePicker();
        questionsScrollPane = new javax.swing.JScrollPane();
        questionsPanel = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        actionCreatePanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        actionConfirmPanel = new javax.swing.JPanel();
        createConfirmBtton = new javax.swing.JButton();
        createBackButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        descriptionLabel.setText("Description:");

        titleLabel.setText("Title:");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(3);
        descriptionScrollPane.setViewportView(descriptionTextArea);

        durationLabel.setText("Duration:");

        pauseDurationLabel.setText("Max pause:");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descriptionLabel)
                    .addComponent(titleLabel))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                                .addComponent(pauseDurationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(pauseDurationTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                                .addComponent(durationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(durationTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(titleTextField))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durationTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationLabel))
                        .addGap(18, 18, 18)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pauseDurationTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pauseDurationLabel)))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel))
                        .addGap(18, 18, 18)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLabel)
                            .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        questionsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        questionsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        questionsPanel.setLayout(new jquiz.swing.WrapLayout());
        questionsScrollPane.setViewportView(questionsPanel);

        actionPanel.setLayout(new java.awt.CardLayout());

        actionCreatePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                actionCreatePanelComponentShown(evt);
            }
        });

        createButton.setText("Create quiz");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add question");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove question");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionCreatePanelLayout = new javax.swing.GroupLayout(actionCreatePanel);
        actionCreatePanel.setLayout(actionCreatePanelLayout);
        actionCreatePanelLayout.setHorizontalGroup(
            actionCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionCreatePanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(actionCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(actionCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        actionCreatePanelLayout.setVerticalGroup(
            actionCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionCreatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addGap(18, 18, 18)
                .addGroup(actionCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(backButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actionPanel.add(actionCreatePanel, "createCard");

        actionConfirmPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                actionConfirmPanelComponentShown(evt);
            }
        });

        createConfirmBtton.setText("Confirm creation");
        createConfirmBtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConfirmBttonActionPerformed(evt);
            }
        });

        createBackButton.setText("Back");
        createBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionConfirmPanelLayout = new javax.swing.GroupLayout(actionConfirmPanel);
        actionConfirmPanel.setLayout(actionConfirmPanelLayout);
        actionConfirmPanelLayout.setHorizontalGroup(
            actionConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(actionConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createConfirmBtton, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        actionConfirmPanelLayout.setVerticalGroup(
            actionConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionConfirmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createConfirmBtton)
                .addGap(18, 18, 18)
                .addComponent(createBackButton)
                .addContainerGap())
        );

        actionPanel.add(actionConfirmPanel, "confirmCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(questionsScrollPane)))
                        .addGap(5, 5, 5)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(questionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        mainFrame.createQuizPanelFormComponentHidden(evt);
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        mainFrame.createQuizPanelFormComponentShown(evt);
    }//GEN-LAST:event_formComponentShown

    private void actionCreatePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_actionCreatePanelComponentShown
        mainFrame.createQuizPanelActionCreatePanelComponentShown(evt);
    }//GEN-LAST:event_actionCreatePanelComponentShown

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        mainFrame.createQuizPanelAddButtonActionPerformed(evt);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        mainFrame.createQuizPanelRemoveButtonActionPerformed(evt);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        mainFrame.createQuizPanelCreateButtonActionPerformed(evt);
    }//GEN-LAST:event_createButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mainFrame.createQuizPanelBackButtonActionPerformed(evt);
    }//GEN-LAST:event_backButtonActionPerformed

    private void actionConfirmPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_actionConfirmPanelComponentShown
        mainFrame.createQuizPanelActionConfirmPanelComponentShown(evt);
    }//GEN-LAST:event_actionConfirmPanelComponentShown

    private void createConfirmBttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConfirmBttonActionPerformed
        mainFrame.createQuizPanelCreateConfirmButtonActionPerformed(evt);
    }//GEN-LAST:event_createConfirmBttonActionPerformed

    private void createBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBackButtonActionPerformed
        mainFrame.createQuizPanelCreateBackButtonActionPerformed(evt);
    }//GEN-LAST:event_createBackButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel actionConfirmPanel;
    public javax.swing.JPanel actionCreatePanel;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createBackButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton createConfirmBtton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    public javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel durationLabel;
    public com.github.lgooddatepicker.components.TimePicker durationTimePicker;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel pauseDurationLabel;
    public com.github.lgooddatepicker.components.TimePicker pauseDurationTimePicker;
    public javax.swing.JPanel questionsPanel;
    public javax.swing.JScrollPane questionsScrollPane;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
