/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jquiz.panels;

import jquiz.MainFrame;
import jquiz.swing.JDebouncedInputValidator;

/**
 *
 * @author ratul
 */
public class LoginPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    public JDebouncedInputValidator emailTextFieldValidator;
    public JDebouncedInputValidator passwordPasswordFieldValidator;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    public LoginPanel(MainFrame mainFrame) {
        this();
        setVisible(false);
        this.mainFrame = mainFrame;

        emailTextFieldValidator = new JDebouncedInputValidator(emailTextField) {
            @Override
            protected com.alexandriasoftware.swing.Validation getDebouncedValidation(
                    javax.swing.JComponent input, com.alexandriasoftware.swing.JInputValidatorPreferences preferences) {
                return emailTextFieldGetDebouncedValidation(input, preferences);
            }
        };

        passwordPasswordFieldValidator = new JDebouncedInputValidator(passwordPasswordField) {
            @Override
            protected com.alexandriasoftware.swing.Validation getDebouncedValidation(
                    javax.swing.JComponent input, com.alexandriasoftware.swing.JInputValidatorPreferences preferences) {
                return passwordPasswordFieldGetDebouncedValidation(input, preferences);
            }
        };

        javax.swing.event.DocumentListener registerButtonDocumentListener = new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent evt) {
                registerButtonDocumentUpdate(evt);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent evt) {
                registerButtonDocumentUpdate(evt);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent evt) {
                registerButtonDocumentUpdate(evt);
            }
        };

        emailTextField.getDocument().addDocumentListener(registerButtonDocumentListener);
        passwordPasswordField.getDocument().addDocumentListener(registerButtonDocumentListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordPasswordField = new javax.swing.JPasswordField();
        actionPanel = new javax.swing.JPanel();
        showCheckBox = new javax.swing.JCheckBox();
        rememberCheckBox = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        forgotPasswordButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        emailLabel.setText("E-mail address:");

        passwordLabel.setText("Password:");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordPasswordField)
                    .addComponent(emailTextField))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        showCheckBox.setText("Show password");
        showCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCheckBoxActionPerformed(evt);
            }
        });

        rememberCheckBox.setText("Remember login");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        forgotPasswordButton.setText("Forgot password");
        forgotPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCheckBox)
                    .addComponent(rememberCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forgotPasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showCheckBox)
                .addGap(18, 18, 18)
                .addComponent(rememberCheckBox)
                .addGap(18, 18, 18)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(loginButton))
                .addGap(18, 18, 18)
                .addComponent(forgotPasswordButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        mainFrame.loginPanelFormComponentHidden(evt);
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        mainFrame.loginPanelFormComponentShown(evt);
    }//GEN-LAST:event_formComponentShown

    private void showCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCheckBoxActionPerformed
        mainFrame.loginPanelShowCheckBoxActionPerformed(evt);
    }//GEN-LAST:event_showCheckBoxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        mainFrame.loginPanelLoginButtonActionPerformed(evt);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        mainFrame.loginPanelRegisterButtonActionPerformed(evt);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void forgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordButtonActionPerformed
        mainFrame.loginPanelForgotPasswordButtonActionPerformed(evt);
    }//GEN-LAST:event_forgotPasswordButtonActionPerformed

    private com.alexandriasoftware.swing.Validation emailTextFieldGetDebouncedValidation(
            javax.swing.JComponent input, com.alexandriasoftware.swing.JInputValidatorPreferences preferences) {
        return mainFrame.loginPanelEmailTextFieldGetDebouncedValidation(input, preferences);
    }

    private com.alexandriasoftware.swing.Validation passwordPasswordFieldGetDebouncedValidation(
            javax.swing.JComponent input, com.alexandriasoftware.swing.JInputValidatorPreferences preferences) {
        return mainFrame.loginPanelPasswordPasswordFieldGetDebouncedValidation(input, preferences);
    }

    private void registerButtonDocumentUpdate(javax.swing.event.DocumentEvent evt) {
        mainFrame.loginPanelRegisterButtonDocumentUpdate(evt);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JLabel emailLabel;
    public javax.swing.JTextField emailTextField;
    private javax.swing.JButton forgotPasswordButton;
    private javax.swing.JPanel inputPanel;
    public javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    public javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JButton registerButton;
    public javax.swing.JCheckBox rememberCheckBox;
    public javax.swing.JCheckBox showCheckBox;
    // End of variables declaration//GEN-END:variables
}
