/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jquiz.panels;

import jquiz.MainFrame;

/**
 *
 * @author ratul
 */
public class ProfilePanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    public ProfilePanel(MainFrame mainFrame) {
        this();
        setVisible(false);
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetingLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailValueLabel = new javax.swing.JLabel();
        quizzesLabel = new javax.swing.JLabel();
        quizzesValueLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        resetPasswordButton = new javax.swing.JButton();
        createQuizButton = new javax.swing.JButton();
        quizListButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        greetingLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        greetingLabel.setText("Good %time!");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setText("%name");

        emailLabel.setText("E-mail:");

        emailValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailValueLabel.setText("%email");

        quizzesLabel.setText("Quizzes:");

        quizzesValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quizzesValueLabel.setText("%quizzes");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        resetPasswordButton.setText("Reset password");
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });

        createQuizButton.setText("Create quiz");
        createQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuizButtonActionPerformed(evt);
            }
        });

        quizListButton.setText("Quiz list");
        quizListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 320, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(resetPasswordButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createQuizButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quizzesLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(quizzesValueLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(emailLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(emailValueLabel))
                                    .addComponent(nameLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizListButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(greetingLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton)
                .addGap(31, 31, 31)
                .addComponent(greetingLabel)
                .addGap(30, 30, 30)
                .addComponent(nameLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailValueLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quizzesLabel)
                    .addComponent(quizzesValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createQuizButton)
                    .addComponent(quizListButton)
                    .addComponent(resetPasswordButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        mainFrame.profilePanelFormComponentShown(evt);
    }//GEN-LAST:event_formComponentShown

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainFrame.profilePanelLogoutButtonActionPerformed(evt);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        mainFrame.profilePanelResetPasswordButtonActionPerformed(evt);
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void createQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQuizButtonActionPerformed
        mainFrame.profilePanelCreateQuizButtonActionPerformed(evt);
    }//GEN-LAST:event_createQuizButtonActionPerformed

    private void quizListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizListButtonActionPerformed
        mainFrame.profilePanelQuizListButtonActionPerformed(evt);
    }//GEN-LAST:event_quizListButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createQuizButton;
    private javax.swing.JLabel emailLabel;
    public javax.swing.JLabel emailValueLabel;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JButton logoutButton;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JButton quizListButton;
    private javax.swing.JLabel quizzesLabel;
    public javax.swing.JLabel quizzesValueLabel;
    private javax.swing.JButton resetPasswordButton;
    // End of variables declaration//GEN-END:variables
}
