/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jquiz.panels;

/**
 *
 * @author ratul
 */
public class SubmitQuestionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubmitQuestionPanel
     */
    public SubmitQuestionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsButtonGroup = new javax.swing.ButtonGroup();
        nLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        hintButton = new javax.swing.JButton();
        optionsPanel = new javax.swing.JPanel();
        option0RadioButton = new javax.swing.JRadioButton();
        option1RadioButton = new javax.swing.JRadioButton();
        option2RadioButton = new javax.swing.JRadioButton();
        option3RadioButton = new javax.swing.JRadioButton();

        setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));

        nLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nLabel.setText("%n.");

        textLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textLabel.setText("%text");

        hintButton.setText("?");

        optionsPanel.setLayout(new java.awt.GridLayout(2, 2));

        optionsButtonGroup.add(option0RadioButton);
        option0RadioButton.setText("%option0");
        option0RadioButton.setActionCommand("0");
        optionsPanel.add(option0RadioButton);

        optionsButtonGroup.add(option1RadioButton);
        option1RadioButton.setText("%option1");
        option1RadioButton.setActionCommand("1");
        optionsPanel.add(option1RadioButton);

        optionsButtonGroup.add(option2RadioButton);
        option2RadioButton.setText("%option2");
        option2RadioButton.setActionCommand("2");
        optionsPanel.add(option2RadioButton);

        optionsButtonGroup.add(option3RadioButton);
        option3RadioButton.setText("%option3");
        option3RadioButton.setActionCommand("3");
        optionsPanel.add(option3RadioButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hintButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel)
                    .addComponent(nLabel)
                    .addComponent(hintButton))
                .addGap(18, 18, 18)
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton hintButton;
    public javax.swing.JLabel nLabel;
    public javax.swing.JRadioButton option0RadioButton;
    public javax.swing.JRadioButton option1RadioButton;
    public javax.swing.JRadioButton option2RadioButton;
    public javax.swing.JRadioButton option3RadioButton;
    public javax.swing.ButtonGroup optionsButtonGroup;
    private javax.swing.JPanel optionsPanel;
    public javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
