/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jquiz.panels;

import jquiz.Const;
import jquiz.MainFrame;

/**
 *
 * @author ratul
 */
public class SubmitQuizPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form SubmitQuizPanel
     */
    public SubmitQuizPanel() {
        initComponents();
    }

    public SubmitQuizPanel(MainFrame mainFrame) {
        this();
        setVisible(false);
        this.mainFrame = mainFrame;

        pauseDurationCountDown.setDateFormat(Const.PAUSE_DURATION_COUNT_DOWN_PATTERN);
        durationCountDown.setDateFormat(Const.DURATION_COUNT_DOWN_PATTERN);

        pauseDurationCountDown.setActionListener((java.awt.event.ActionEvent evt) -> {
            pauseDurationCountDownActionPerformed(evt);
        });

        durationCountDown.setActionListener((java.awt.event.ActionEvent evt) -> {
            durationCountDownActionPerformed(evt);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleValueLabel = new javax.swing.JLabel();
        quizerLabel = new javax.swing.JLabel();
        quizerValueLabel = new javax.swing.JLabel();
        descriptionButton = new javax.swing.JButton();
        pauseDurationLabel = new javax.swing.JLabel();
        pauseDurationCountDown = new jquiz.components.JCountDown();
        durationLabel = new javax.swing.JLabel();
        durationCountDown = new jquiz.components.JCountDown();
        optionalQuestionsPanel = new javax.swing.JPanel();
        questionsScrollPane = new javax.swing.JScrollPane();
        questionsPanel = new javax.swing.JPanel();
        pausedPanel = new javax.swing.JPanel();
        pausedLabel = new javax.swing.JLabel();
        resumeLabel = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        actionSubmitPanel = new javax.swing.JPanel();
        pauseToggleButton = new javax.swing.JToggleButton();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        actionConfirmPanel = new javax.swing.JPanel();
        submitConfirmButton = new javax.swing.JButton();
        backConfirmButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        titleLabel.setText("Title:");

        titleValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleValueLabel.setText("%title");

        quizerLabel.setText("Quizer:");

        quizerValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quizerValueLabel.setText("%quizer");

        descriptionButton.setText("?");

        pauseDurationLabel.setText("Pause left:");

        pauseDurationCountDown.setText("00:00");
        pauseDurationCountDown.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        durationLabel.setText("Time left:");

        durationCountDown.setText("00:00:00.000");
        durationCountDown.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quizerLabel)
                    .addComponent(titleLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleValueLabel)
                    .addComponent(quizerValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pauseDurationLabel)
                    .addComponent(durationLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(pauseDurationCountDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descriptionButton))
                    .addComponent(durationCountDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleValueLabel)
                    .addComponent(descriptionButton)
                    .addComponent(titleLabel)
                    .addComponent(pauseDurationCountDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pauseDurationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quizerLabel)
                    .addComponent(quizerValueLabel)
                    .addComponent(durationCountDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLabel))
                .addContainerGap())
        );

        optionalQuestionsPanel.setLayout(new java.awt.CardLayout());

        questionsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        questionsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        questionsPanel.setLayout(new jquiz.swing.WrapLayout());
        questionsScrollPane.setViewportView(questionsPanel);

        optionalQuestionsPanel.add(questionsScrollPane, "card2");

        pausedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pausedLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pausedLabel.setText("Quiz paused!");

        resumeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resumeLabel.setText("Click \"Resume\" to continue!");

        javax.swing.GroupLayout pausedPanelLayout = new javax.swing.GroupLayout(pausedPanel);
        pausedPanel.setLayout(pausedPanelLayout);
        pausedPanelLayout.setHorizontalGroup(
            pausedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pausedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pausedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resumeLabel)
                    .addComponent(pausedLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pausedPanelLayout.setVerticalGroup(
            pausedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pausedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pausedLabel)
                .addGap(18, 18, 18)
                .addComponent(resumeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionalQuestionsPanel.add(pausedPanel, "card3");

        actionPanel.setLayout(new java.awt.CardLayout());

        actionSubmitPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                actionSubmitPanelComponentShown(evt);
            }
        });

        pauseToggleButton.setText("%pause");
        pauseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseToggleButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionSubmitPanelLayout = new javax.swing.GroupLayout(actionSubmitPanel);
        actionSubmitPanel.setLayout(actionSubmitPanelLayout);
        actionSubmitPanelLayout.setHorizontalGroup(
            actionSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionSubmitPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(actionSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionSubmitPanelLayout.createSequentialGroup()
                        .addComponent(pauseToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        actionSubmitPanelLayout.setVerticalGroup(
            actionSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionSubmitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(pauseToggleButton))
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap())
        );

        actionPanel.add(actionSubmitPanel, "submitCard");

        actionConfirmPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                actionConfirmPanelComponentShown(evt);
            }
        });

        submitConfirmButton.setText("Confirm submission");
        submitConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitConfirmButtonActionPerformed(evt);
            }
        });

        backConfirmButton.setText("Back");
        backConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionConfirmPanelLayout = new javax.swing.GroupLayout(actionConfirmPanel);
        actionConfirmPanel.setLayout(actionConfirmPanelLayout);
        actionConfirmPanelLayout.setHorizontalGroup(
            actionConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(actionConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        actionConfirmPanelLayout.setVerticalGroup(
            actionConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionConfirmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitConfirmButton)
                .addGap(18, 18, 18)
                .addComponent(backConfirmButton)
                .addContainerGap())
        );

        actionPanel.add(actionConfirmPanel, "confirmCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(optionalQuestionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionalQuestionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        mainFrame.submitQuizPanelFormComponentHidden(evt);
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        mainFrame.submitQuizPanelFormComponentShown(evt);
    }//GEN-LAST:event_formComponentShown

    private void actionSubmitPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_actionSubmitPanelComponentShown
        mainFrame.submitQuizPanelActionSubmitPanelComponentShown(evt);
    }//GEN-LAST:event_actionSubmitPanelComponentShown

    private void pauseToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseToggleButtonActionPerformed
        mainFrame.submitQuizPanelPauseToggleButtonActionPerformed(evt);
    }//GEN-LAST:event_pauseToggleButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        mainFrame.submitQuizPanelSubmitButtonActionPerformed(evt);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mainFrame.submitQuizPanelBackButtonActionPerformed(evt);
    }//GEN-LAST:event_backButtonActionPerformed

    private void actionConfirmPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_actionConfirmPanelComponentShown
        mainFrame.submitQuizPanelActionConfirmPanelComponentShown(evt);
    }//GEN-LAST:event_actionConfirmPanelComponentShown

    private void submitConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitConfirmButtonActionPerformed
        mainFrame.submitQuizPanelSubmitConfirmButtonActionPerformed(evt);
    }//GEN-LAST:event_submitConfirmButtonActionPerformed

    private void backConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backConfirmButtonActionPerformed
        mainFrame.submitQuizPanelBackConfirmButtonActionPerformed(evt);
    }//GEN-LAST:event_backConfirmButtonActionPerformed

    private void pauseDurationCountDownActionPerformed(java.awt.event.ActionEvent evt) {
        mainFrame.submitQuizPanelPauseDurationCountDownActionPerformed(evt);
    }

    private void durationCountDownActionPerformed(java.awt.event.ActionEvent evt) {
        mainFrame.submitQuizPanelDurationCountDownActionPerformed(evt);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel actionConfirmPanel;
    private javax.swing.JPanel actionPanel;
    public javax.swing.JPanel actionSubmitPanel;
    public javax.swing.JButton backButton;
    public javax.swing.JButton backConfirmButton;
    private javax.swing.JButton descriptionButton;
    public jquiz.components.JCountDown durationCountDown;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel optionalQuestionsPanel;
    public jquiz.components.JCountDown pauseDurationCountDown;
    private javax.swing.JLabel pauseDurationLabel;
    public javax.swing.JToggleButton pauseToggleButton;
    private javax.swing.JLabel pausedLabel;
    public javax.swing.JPanel pausedPanel;
    public javax.swing.JPanel questionsPanel;
    public javax.swing.JScrollPane questionsScrollPane;
    private javax.swing.JLabel quizerLabel;
    public javax.swing.JLabel quizerValueLabel;
    private javax.swing.JLabel resumeLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitConfirmButton;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JLabel titleValueLabel;
    // End of variables declaration//GEN-END:variables
}
